#all: blocks_raw transactions_raw logs_raw

#blocks_raw:
#	protoc -I=. --python_out=../protobuf_compiled/ ./blocks_raw.proto;

transactions_raw:
	protoc -I=. --python_out=./ ./transaction_raw.proto;

#logs_raw:
#	protoc -I=. --python_out=../protobuf_compiled/. ./logs_raw.proto;
