"""v0.3.0-ecosystem

Revision ID: 5d35947228b7
Revises: cbe1e6b0a6b9
Create Date: 2024-02-26 20:26:53.150256

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d35947228b7"
down_revision: Union[str, None] = "cbe1e6b0a6b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ecosystem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transactions_24h", sa.Integer(), nullable=True),
        sa.Column("transactions_7d", sa.Integer(), nullable=True),
        sa.Column("transactions_30d", sa.Integer(), nullable=True),
        sa.Column("transactions_24h_prev", sa.Integer(), nullable=True),
        sa.Column("transactions_7d_prev", sa.Integer(), nullable=True),
        sa.Column("transactions_30d_prev", sa.Integer(), nullable=True),
        sa.Column("fees_burned_24h", sa.Integer(), nullable=True),
        sa.Column("fees_burned_7d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_30d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_24h_prev", sa.Integer(), nullable=True),
        sa.Column("fees_burned_7d_prev", sa.Integer(), nullable=True),
        sa.Column("fees_burned_30d_prev", sa.Integer(), nullable=True),
        sa.Column("transaction_addresses_24h", sa.Integer(), nullable=True),
        sa.Column("transaction_addresses_7d", sa.Integer(), nullable=True),
        sa.Column("transaction_addresses_30d", sa.Integer(), nullable=True),
        sa.Column("transaction_addresses_24h_prev", sa.Integer(), nullable=True),
        sa.Column("transaction_addresses_7d_prev", sa.Integer(), nullable=True),
        sa.Column("transaction_addresses_30d_prev", sa.Integer(), nullable=True),
        sa.Column("token_transfers_24h", sa.Integer(), nullable=True),
        sa.Column("token_transfers_7d", sa.Integer(), nullable=True),
        sa.Column("token_transfers_30d", sa.Integer(), nullable=True),
        sa.Column("token_transfers_24h_prev", sa.Integer(), nullable=True),
        sa.Column("token_transfers_7d_prev", sa.Integer(), nullable=True),
        sa.Column("token_transfers_30d_prev", sa.Integer(), nullable=True),
        sa.Column("token_transfer_addresses_24h", sa.Integer(), nullable=True),
        sa.Column("token_transfer_addresses_7d", sa.Integer(), nullable=True),
        sa.Column("token_transfer_addresses_30d", sa.Integer(), nullable=True),
        sa.Column("token_transfer_addresses_24h_prev", sa.Integer(), nullable=True),
        sa.Column("token_transfer_addresses_7d_prev", sa.Integer(), nullable=True),
        sa.Column("token_transfer_addresses_30d_prev", sa.Integer(), nullable=True),
        sa.Column("last_updated_timestamp", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        schema="stats",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ecosystem", schema="stats")
    # ### end Alembic commands ###
