"""v0.1.0-init

Revision ID: 75a20dabc6fc
Revises:
Create Date: 2024-02-12 23:31:19.943371

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75a20dabc6fc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("logo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("transactions_24h", sa.Integer(), nullable=True),
        sa.Column("transactions_7d", sa.Integer(), nullable=True),
        sa.Column("transactions_30d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_24h", sa.Integer(), nullable=True),
        sa.Column("fees_burned_7d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_30d", sa.Integer(), nullable=True),
        sa.Column("token_transfers_24h", sa.Integer(), nullable=True),
        sa.Column("token_transfers_7d", sa.Integer(), nullable=True),
        sa.Column("token_transfers_30d", sa.Integer(), nullable=True),
        sa.Column("volume_24h", sa.Float(), nullable=True),
        sa.Column("volume_7d", sa.Float(), nullable=True),
        sa.Column("volume_30d", sa.Float(), nullable=True),
        sa.Column("last_updated_timestamp", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="stats",
    )
    op.create_table(
        "contracts",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("application_id", sa.String(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transactions_24h", sa.Integer(), nullable=True),
        sa.Column("transactions_7d", sa.Integer(), nullable=True),
        sa.Column("transactions_30d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_24h", sa.Integer(), nullable=True),
        sa.Column("fees_burned_7d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_30d", sa.Integer(), nullable=True),
        sa.Column("last_updated_timestamp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["stats.applications.id"],
        ),
        sa.PrimaryKeyConstraint("address", "application_id"),
        sa.UniqueConstraint("address"),
        schema="stats",
    )
    op.create_table(
        "tokens",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("volume_24h", sa.Float(), nullable=True),
        sa.Column("volume_7d", sa.Float(), nullable=True),
        sa.Column("volume_30d", sa.Float(), nullable=True),
        sa.Column("token_transfers_24h", sa.Integer(), nullable=True),
        sa.Column("token_transfers_7d", sa.Integer(), nullable=True),
        sa.Column("token_transfers_30d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_24h", sa.Integer(), nullable=True),
        sa.Column("fees_burned_7d", sa.Integer(), nullable=True),
        sa.Column("fees_burned_30d", sa.Integer(), nullable=True),
        sa.Column("last_updated_timestamp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address"],
            ["stats.contracts.address"],
        ),
        sa.PrimaryKeyConstraint("address"),
        schema="stats",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens", schema="stats")
    op.drop_table("contracts", schema="stats")
    op.drop_table("applications", schema="stats")
    # ### end Alembic commands ###
