"""v0.1.0-cmc-listings-quote

Revision ID: b2a3b4700296
Revises: 
Create Date: 2023-10-26 20:57:20.781061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b2a3b4700296'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmc',
    sa.Column('base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('volume_change_24h', sa.Float(), nullable=False),
    sa.Column('percent_change_1h', sa.Float(), nullable=False),
    sa.Column('percent_change_24h', sa.Float(), nullable=False),
    sa.Column('percent_change_7d', sa.Float(), nullable=False),
    sa.Column('percent_change_30d', sa.Float(), nullable=False),
    sa.Column('percent_change_60d', sa.Float(), nullable=False),
    sa.Column('percent_change_90d', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('market_cap_dominance', sa.Float(), nullable=False),
    sa.Column('fully_diluted_market_cap', sa.Float(), nullable=False),
    sa.Column('tvl', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('base', 'quote', 'last_updated'),
    schema='stats'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmc', schema='stats')
    # ### end Alembic commands ###
