"""v0.1.1-unique-addresses

Revision ID: c02c2fa1061d
Revises: 75a20dabc6fc
Create Date: 2024-02-13 23:42:42.013180

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c02c2fa1061d"
down_revision: Union[str, None] = "75a20dabc6fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contracts", sa.Column("unique_addresses_24h", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("unique_addresses_7d", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("unique_addresses_30d", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("unique_addresses_24h", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("unique_addresses_7d", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("unique_addresses_30d", sa.Integer(), nullable=True), schema="stats"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "unique_addresses_30d", schema="stats")
    op.drop_column("tokens", "unique_addresses_7d", schema="stats")
    op.drop_column("tokens", "unique_addresses_24h", schema="stats")
    op.drop_column("contracts", "unique_addresses_30d", schema="stats")
    op.drop_column("contracts", "unique_addresses_7d", schema="stats")
    op.drop_column("contracts", "unique_addresses_24h", schema="stats")
    # ### end Alembic commands ###
