"""v0.3.0-all-tokens

Revision ID: cbe1e6b0a6b9
Revises: 3834262fdf64
Create Date: 2024-02-17 01:56:19.089814

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbe1e6b0a6b9"
down_revision: Union[str, None] = "3834262fdf64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("transactions_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("transactions_7d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("transactions_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("fees_burned_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("fees_burned_7d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("fees_burned_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("transaction_addresses_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("transaction_addresses_7d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("transaction_addresses_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("token_transfers_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("token_transfers_7d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("token_transfers_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications", sa.Column("volume_24h_prev", sa.Float(), nullable=True), schema="stats"
    )
    op.add_column(
        "applications", sa.Column("volume_7d_prev", sa.Float(), nullable=True), schema="stats"
    )
    op.add_column(
        "applications", sa.Column("volume_30d_prev", sa.Float(), nullable=True), schema="stats"
    )
    op.add_column(
        "applications",
        sa.Column("token_transfer_addresses_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("token_transfer_addresses_7d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "applications",
        sa.Column("token_transfer_addresses_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "contracts", sa.Column("transactions_24h_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("transactions_7d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("transactions_30d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("fees_burned_24h_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("fees_burned_7d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts", sa.Column("fees_burned_30d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "contracts",
        sa.Column("unique_addresses_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "contracts",
        sa.Column("unique_addresses_7d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "contracts",
        sa.Column("unique_addresses_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "tokens", sa.Column("token_transfers_24h_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("token_transfers_7d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("token_transfers_30d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("fees_burned_24h_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("fees_burned_7d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens", sa.Column("fees_burned_30d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens",
        sa.Column("unique_addresses_24h_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    op.add_column(
        "tokens", sa.Column("unique_addresses_7d_prev", sa.Integer(), nullable=True), schema="stats"
    )
    op.add_column(
        "tokens",
        sa.Column("unique_addresses_30d_prev", sa.Integer(), nullable=True),
        schema="stats",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "unique_addresses_30d_prev", schema="stats")
    op.drop_column("tokens", "unique_addresses_7d_prev", schema="stats")
    op.drop_column("tokens", "unique_addresses_24h_prev", schema="stats")
    op.drop_column("tokens", "fees_burned_30d_prev", schema="stats")
    op.drop_column("tokens", "fees_burned_7d_prev", schema="stats")
    op.drop_column("tokens", "fees_burned_24h_prev", schema="stats")
    op.drop_column("tokens", "token_transfers_30d_prev", schema="stats")
    op.drop_column("tokens", "token_transfers_7d_prev", schema="stats")
    op.drop_column("tokens", "token_transfers_24h_prev", schema="stats")
    op.drop_column("contracts", "unique_addresses_30d_prev", schema="stats")
    op.drop_column("contracts", "unique_addresses_7d_prev", schema="stats")
    op.drop_column("contracts", "unique_addresses_24h_prev", schema="stats")
    op.drop_column("contracts", "fees_burned_30d_prev", schema="stats")
    op.drop_column("contracts", "fees_burned_7d_prev", schema="stats")
    op.drop_column("contracts", "fees_burned_24h_prev", schema="stats")
    op.drop_column("contracts", "transactions_30d_prev", schema="stats")
    op.drop_column("contracts", "transactions_7d_prev", schema="stats")
    op.drop_column("contracts", "transactions_24h_prev", schema="stats")
    op.drop_column("applications", "token_transfer_addresses_30d_prev", schema="stats")
    op.drop_column("applications", "token_transfer_addresses_7d_prev", schema="stats")
    op.drop_column("applications", "token_transfer_addresses_24h_prev", schema="stats")
    op.drop_column("applications", "volume_30d_prev", schema="stats")
    op.drop_column("applications", "volume_7d_prev", schema="stats")
    op.drop_column("applications", "volume_24h_prev", schema="stats")
    op.drop_column("applications", "token_transfers_30d_prev", schema="stats")
    op.drop_column("applications", "token_transfers_7d_prev", schema="stats")
    op.drop_column("applications", "token_transfers_24h_prev", schema="stats")
    op.drop_column("applications", "transaction_addresses_30d_prev", schema="stats")
    op.drop_column("applications", "transaction_addresses_7d_prev", schema="stats")
    op.drop_column("applications", "transaction_addresses_24h_prev", schema="stats")
    op.drop_column("applications", "fees_burned_30d_prev", schema="stats")
    op.drop_column("applications", "fees_burned_7d_prev", schema="stats")
    op.drop_column("applications", "fees_burned_24h_prev", schema="stats")
    op.drop_column("applications", "transactions_30d_prev", schema="stats")
    op.drop_column("applications", "transactions_7d_prev", schema="stats")
    op.drop_column("applications", "transactions_24h_prev", schema="stats")
    # ### end Alembic commands ###
