name: push-main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Install deps
#        run: |
#          pip3 install -r requirements-api.txt \
#          -r requirements-streaming.txt \
#          -r requirements-cron.txt \
#          -r requirements-common.txt \
#          -r requirements-dev.txt

# #   TODO: Fix tests - They run out of order and are flakey - best to just do tests
# #    locally - not in CI...
#      - name: Bring up stack
#        run: make up-dbs && sleep 30
#
#      - name: Check stack
#        run: make ps
#
#      - name: Run tests with coverage
#        run: make test-coverage
#
#      - uses: codecov/codecov-action@v2
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: ./coverage.xml
#          fail_ci_if_error: true

  docker:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      tag: ${{ steps.source.outputs.TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: last
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${{ steps.last.outputs.release }}-${{ github.run_number }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            SERVICE_NAME=api
          tags: sudoblock/icon-stats-api:latest, sudoblock/icon-stats-api:${{ steps.source.outputs.TAG }}

      - name: Build and push cron
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            SERVICE_NAME=cron
          tags: sudoblock/icon-stats-cron:latest, sudoblock/icon-stats-cron:${{ steps.source.outputs.TAG }}

#      - name: Build and push streaming
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          build-args: |
#            SERVICE_NAME=streaming
#          tags: sudoblock/icon-stats-streaming:latest, sudoblock/icon-stats-streaming:${{ steps.source.outputs.TAG }}


  push_refs:
    runs-on: ubuntu-latest
    needs: docker
    strategy:
      max-parallel: 1
      matrix:
        include:
          - cluster: cluster2
            network_name: mainnet
            network_version: v2
          - cluster: cluster2
            network_name: lisbon
            network_version: v2
          - cluster: cluster2
            network_name: berlin
            network_version: v2

    steps:

      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: sudoblockio/icon-charts
          ref: main
          path: charts
          token: ${{ secrets.ICON_CHARTS_PAT }}

      - name: Update API ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} deployment values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: sudoblockio/icon-charts
          valueFile: 'deployments/${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }}/stats/tags.yaml'
          propertyPath: 'api.image.tag'
          value: ${{needs.docker.outputs.tag}}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update cron ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} deployment values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: sudoblockio/icon-charts
          valueFile: 'deployments/${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }}/stats/tags.yaml'
          propertyPath: 'cron.image.tag'
          value: ${{needs.docker.outputs.tag}}
          branch: main
          createPR: 'false'
          updateFile: true
          message: "stats ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} deployment image version to ${{needs.docker.outputs.tag}}"
          token: '${{ secrets.ICON_CHARTS_PAT }}'

      - name: Update streaming ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} deployment values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: sudoblockio/icon-charts
          valueFile: 'deployments/${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }}/stats/tags.yaml'
          propertyPath: 'streaming.image.tag'
          value: ${{needs.docker.outputs.tag}}
          branch: main
          createPR: 'false'
          updateFile: true
          message: "stats ${{ matrix.cluster }}/${{ matrix.network_name }}-${{ matrix.network_version }} deployment image version to ${{needs.docker.outputs.tag}}"
          token: '${{ secrets.ICON_CHARTS_PAT }}'
